name = input("Enter your name: ")
age = input("Enter your age: ")
place = input("Enter your place: ")
education = input("Enter your education: ")
school = input("Enter your school name: ")
qualification = input("Enter your qualification: ")
print("Name:", name)
print("Age:", age)
print("Place:", place)
print("Education:", education)
print("School:", school)
print("Qualification:", qualification)
